### ISSUE TITLE
meshage: restore mesh timeout

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#1004]
See https://github.com/sandia-minimega/minimega/pull/505

We need this back and tested.

**Comment by jcrussell** [comment]
This isn't an issue -- `mesh timeout` API still exists, it's just set to "unlimited" by default.

Perhaps it would be useful to "pump" meshage when a node disconnects so that we stop waiting on a response from it. This would allow you to keep the timeout as "unlimited" but continue if nodes drop out.
