### ISSUE TITLE
vm config clone breaks networking

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#1072]
Boot a VM with networking
```
vlans range 1890 1900
clear vm config 
vm config cdrom linux.iso
vm config net A
vm launch kvm linux
vm start linux
```
Now clone the config, kill the vm, and start it again
```
vm config clone linux
vm kill linux
vm flush
clear vm config uuid
vm launch kvm linux
vm start linux
```
Networking will not work for the VM. You need to clear the net variable.

```
vm kill linux
vm flush
clear vm config net
vm config net A
vm launch kvm linux
vm start linux
```
Networking will now work for the VM.

**Comment by jcrussell** [comment]
Pretty sure that I know the problem:
```golang
	for i := range vm.Networks {
		nic := &vm.Networks[i]
		if nic.Tap != "" {
			// tap has already been created, don't need to do again
			continue
		}
```
from `kvm.go:592`. Since we clone the VM config, we already have a tap name. This code should be changed so that we check if the tap is already on the bridge instead.

Should the tap name be cloned though? You probably want a separate tap on the same network, right?

**Comment by mkunz7** [comment]
AFAIK we should be fine with a separate tap on the same network. Not a whole lot of people use the vm config clone function.

**Comment by jcrussell** [comment]
So `vm config clone` will clone the `VLAN`, `Bridge`, and `Driver` from the old VM but create new `Tap` and `MAC` addresses?

@mkunz7 @djfritz -- sound good to you?
