### ISSUE TITLE
hostnames and novnc

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#1151]
Not sure if this is a bug, but If the hostname of a box doesn't resolve, novnc will fail to connect.

For example:
```
# hostname doesnotexist
```
novnc fails to connect to a vm, vm screenshots works just fine
```
# echo "127.0.0.1 doesnotexist" >> /etc/hosts
```
everything is happy

**Comment by djfritz** [comment]
This is almost certainly because of artifacts in namespaces and meshage
where we require hostnames to be sane. Not sure I would call it a bug
without elevating hostname based organization to being an issue.

If this is a local host issue then yea we need to switch/try/something with
“localhost” mappings.

**Comment by mkunz7** [comment]
Not sure if it is a local host issue, but it happens when I run experiments with just one node

**Comment by jcrussell** [comment]
We use hostnames in a bunch of places, it seems reasonable to make it a requirement to have them resolve in order to use minimega.

@mkunz7: reopen if you object.
