### ISSUE TITLE
minimega: support ranges and lists for vm commands

### ISSUE THREAD

**Issue by bjwrigh** [sandia-minimega/minimega#186]
'vm lock vm-0' would allow a vm to be immune to 'vm kill all'  in order to facilitate a special vm to maintain state while cycling the environment around the locked VMs.

**Comment by djfritz** [comment]
this is too messy. I'd support a regexp in vm kill before this:

vm kill router*, etc...

**Comment by bjwrigh** [comment]
that'll be good enough.  @djfritz

**Comment by jcrussell** [comment]
If we add regexp support for `vm kill`, shouldn't we add it for all vm commands? Do we really want to do that?

If I were interfacing with minimega in python, I would do a `vm list` and regexp the names myself to figure out the full list of vms to kill.

**Comment by djfritz** [comment]
It only makes sense in the current API to add this to kill, start, and stop. Instead of a regexp, I think it's simpler and still useful to just apply the ranges semantics we use in mesh commands. Some patterns examples:

vm start <name, id, all, or range/list>

vm start all
vm start router[1-15]
vm kill router[1-5],foo,bar

I think this is a good idea eventually - right now if you want to kill a specific set of VMs, you have to do so with individual vm kill commands. That's fine in theory, but gets ugly fast in practice - it can take minutes to do something like "kill these 100 vms and then restart them"

@jcrussell @bjwrigh Thoughts?

**Comment by jcrussell** [comment]
Good idea. Shouldn't be too hard to implement either.

**Comment by jcrussell** [comment]
If someone inputs `vm start foo,bar[0-10],all` should we treat this as a wildcard command or throw an error?

**Comment by jcrussell** [comment]
Also, what if they run `vm start foo,bar[0-10]` and bar2 is already started? Should it:

1. print a warning and continue
2. stop when it reaches bar2
3. check ahead of time and not start any vms

**Comment by djfritz** [comment]
Instead of log.Warn, use log.Info. We do this already with things like 'vm start all' - even if everything is already in the running state, it just returns silently (unless there is a real error of course).
