### ISSUE TITLE
qmp: qemu capabilities check is incomplete

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#210]
In qmp:Dial(), we return success if qmp returns even an empty "return" when we issue "qmp capabilities". That's invalid - instead we should retry for some amount of time (5 seconds?), and return an error to the launching vm if qmp cannot dial correctly. This should help alleviate most of the future 'qmp not ready' errors sometimes encountered later on.

**Comment by bjwrigh** [comment]
in an aside to this...  most of our layer3 switch implementations require a
lot of ovs setup, and we see a lot of qmp not ready errors as a result.  i
can provide the environment next week if you'd like to run some tests/get
logs/ and see our strange exit that seems to also happen.  (haven't
reported this behavior due to the inability to take down the test at this
time)
@djfritz @

**Comment by djfritz** [comment]
So qmp redial and ready checks are all in place - what was really happening is that on 'vm start' if the qmp socket really wasn't ready, as is usually the case with scripts like:

    vm launch foo noblock
    vm start foo

minimega would put the vm into the ERROR state, preventing you from ever trying again. Now that we support re-launching ERROR vms, there's an added bug, #209, that causes the VM to launch again and potentially hang minimega.

The behavior is fixed in the above commit - don't put the VM into the ERROR state if you try 'vm start' and the returned error is 'not ready'. That lets you wait and call start again later, which is the desired behavior (put the burden on the user) when using the 'noblock' suffix. 

Note that this error doesn't show up unless there's some other bug when NOT using the 'noblock' suffix, as the ready state must return true before the CLI unblocks.
