### ISSUE TITLE
vm disk image creation pipeline

### ISSUE THREAD

**Issue by bjwrigh** [sandia-minimega/minimega#246]
I've been teaching interns and folks how to create VMs recently...some continuity in the 'minimega wraps all tools' would be nice.

wrap:
qemu-img create -f qcow2 name.qcow2 100G
as:
vm disk create {type(or implied qc2?)} {name} {size}

@djfritz 
Thoughts?

**Comment by floren** [comment]
So the use case here would be you're booting from a Windows CD or something so you can install to the blank disk?

It would  be really easy to do, but we also need to be careful because if you accidentally get this in a script, it could overwrite the image you carefully populated earlier. Maybe that's the desired behavior, or maybe it should refuse to overwrite an existing file.

**Comment by djfritz** [comment]
Or perhaps add an optional "force" keyword in the command.

**Comment by bjwrigh** [comment]
If you are scripting around this, then you should be smart enough to intend
the behavior to 'start from scratch' every time you run the script.

But a force keyword would be a good thing to prevent shenanigans.

**Comment by djfritz** [comment]
With the new 'disk' API: http://tip.minimega.org/articles/api.article#TOC_5.10.

We can add this. I'm on it.
