### ISSUE TITLE
scheduler support

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#3]
Original [issue 3](https://code.google.com/p/minimega/issues/detail?id=3) created by djfritz on 2013-08-29T18:11:11.000Z:

add scheduler support with the following:

  * fanout VMs. Something like &quot;here's a description of a VM, now give me 10000 of those&quot;. It should simply 'schedule' them according to some rules about how to launch VMs.
  * Some rules on how to launch VMs. This includes limits on firing off VMs too quickly (before KSM can work), as well as what nodes the VMs should be restricted to.
  * Additional rule about what vlans to use.
  * schedule should go off in the background - ie not block on the command line until the VMs are launched. That could take forever...
  * information about a schedule. I'm not exactly sure what that means. For now it's just a summary of what's running, what should be running, and so on.

Some examples of usage:
                vm_disk ...
                vm_memory ...
                schedule vlans 1-500,1000-2500
                schedule nodes kn[40-50]
                schedule limit memory 90%
                schedule limit memory 100G
                schedule limit cpu 90%
                schedule net A B C
                schedule launch foo 500
                ...
                schedule kill foo
                schedule summary
                schedule limits
                schedule

**Comment by jcrussell** [comment]
Some decisions:

* enforce globally unique VM names
* `vm kill <id>` is dangerous -- will kill all VMs with given ID
* `vm kill <host>::<name or ID or all>` is redundant -- use `mesh send`

**Comment by jcrussell** [comment]
When we talked about this before, we were discussing the idea of having the `vm ...` commands be namespace aware. For example, if you did `vm config memory 2048`, it would broadcast that config to all the hosts in the namespace and the `vm launch` would decide where VMs should be launched and `mesh send` accordingly. After thinking about this more, I think the `vm ...` commands should be low-level commands used to configure the local node. We discussed this idea before but, to document it here, we would introduce a new command:

`namespace <name> <queue,> <kvm,container> <count>`

to copy the locally configured VMConfig into a queuedVMs slice that can then be executed using:

`namespace <name> <launch,>`

The namespace launch command will then use `vm config ...` over meshage to configure the hosts properly and launch all the queued VMs according to some scheduling algorithm. This avoids some nasty corner cases like when a host is added after some number of `vm config` commands have been executed. It also allows us to make a smarter scheduler by taking into account all the configured VMs in an experiment rather than just the ones currently being launched.

**Comment by jcrussell** [comment]
The above approach seems to be correct for configuring and launching VMs but, for VM lifecycle commands (e.g. start, stop) and listing all the VMs, it puts more burden on the user. Maybe those commands need to be namespace-aware? Or would it make more sense to have namespace'd versions of those commands (e.g. `namespace <name> start <vm name>`)?

**Comment by bjwrigh** [comment]
Can namespace be a single context switch?  Minimega -e .ns name1 VM start
all

Such that once the ns is switched during that context, there is no need to
be explicit?

**Comment by jcrussell** [comment]
@bjwrigh: Yup, you can activate a namespace via `namespace <name>`. By default, all hosts connected to the local instance via meshage are part of the namespace. You can then use the vm commands to launch vms across all the nodes in the namespace.

**Comment by jcrussell** [comment]
Recording history is a bit tricky... do we want the non-head nodes to record the commands sent to them by the scheduler? I'm think not.

@djfritz, @floren: thoughts?

**Comment by djfritz** [comment]
namespace <name> <queue,> <kvm,container> <count>

I don't like this. What we discussed was that we should be able to do a local experiment such as:

    vm config ...
    vm launch ...

And then scale it up seamlessly by simply entering into a namespace and increasing the number of VMs to launch. In this way you can develop an experiment on a single node, and scale up without having to hack the launch script. Even better, if you're doing this outside of minimega script (bash, python, whatever), you could make the scale a parameter. 

@floren

**Comment by djfritz** [comment]
In the sense of the comment above - namespacing here is sort of like a bind mount of multiple nodes - you enter the API as you would on a single node, and things happen seamlessly if you're in a namespace.

**Comment by jcrussell** [comment]
I've since changed my mind on

```namespace <name> <queue,> <kvm,container> <count>```

Instead, it's all done through `vm launch`, when a namespace is active:

```
# queue VMs for launch based on current config
vm launch <kvm,container> <count>

# actually schedule and launch the VMs:
vm launch
```

We could change it so that there's an optional parameter to `vm launch` that controls whether the VMs get queued or not, that would make the launch behavior the same with/without namespaces.

**Comment by jcrussell** [comment]
Hm, should calling `mesh send all` in a namespace only send commands to the hosts in the namespace? I think so but I could be wrong.

We're (I'm) going to need to write a big article describing how this all works.

**Comment by bjwrigh** [comment]
I would say when you are 'in a namespace', it should only interact with
that namespace.

Only global actions should happen when not in a namespace.

(Maybe even a print statement saying you're in a namespace!)

Only my thoughts. @djfritz

**Comment by jcrussell** [comment]
Problem: Currently, we can acquire locks on the head node to ensure the atomicity of commands issued by the scheduler but those aren't guaranteed to be atomic at the remote host. This is especially problematic if two schedulers are trying to boot differently configured VMs on the same remote host.

Idea: Add a .atomic built-in? It would run all the commands that are separated by -- and can stop prematurely if .Error != "".

**Comment by djfritz** [comment]
We talked about grouped commands that are implicitly atomic. On the command line, this would be something like:

    host; vm config disk foo; echo bar

Internally, we could change all references to *minicli.Command to `var type Commands []*minicli.Command` in the same way we deal with multiple responses. A `Commands` object is then executed atomically and doesn't require new API.

Thoughts?

**Comment by jcrussell** [comment]
After thinking about how to implement both these ideas and not coming up with a clean solution, I wonder if we need this at all. Most likely users won't try to run multiple schedulers on separate head nodes that are launching VMs on the same remote host. Currently, if you launch VMs using `mesh send`, you have no guarantees that other meshages aren't reaching the same remote host and being interleaved with the commands you issue. I think this is probably fine given that most users launch everything from a head node. Unless there's strong thoughts otherwise, I'm going to drop this thread and keep working on the common case.

**Comment by jcrussell** [comment]
Remaining TODOs:
 * measurements for scheduler progress
 * Filter `vm info` using namespace
 * Make `vm flush` only apply to VMs in the current namespace
 * Add VLAN aliases to `vm net`

Tricky commands that will need some thought:
 * `bridge`
 * `capture`
 * `cc`

**Comment by jcrussell** [comment]
For `vm net`, are VLAN aliases anything specific to the namespaces? Each namespace would probably have its own set of aliases but other than that, VLAN aliases seems like a generally useful feature. Do we need to have blocks of VLANs reserved for different namespaces? Couldn't we just allocate from the global pool of available VLANs?

For `cc`, most scripts are probably written to `mesh send all` the different `cc` commands -- that should still work. We probably just need to add an extra restriction that the VM's namespace is correct in addition to all the `cc` filters.

For `bridge`/`capture`, how do you think these should work?

@djfritz

**Comment by jcrussell** [comment]
Okay, `vm config net` should be complete (see 22bd9be8285f8ac04a3f9479d00dd300e64ba1ba).

We decided to punt on `cc` and `bridge`/`capture`.

**Comment by djfritz** [comment]
Closing this via the namespaces merge. When the dust settles, we'll open a new ticket for other things on the wishlist.
