### ISSUE TITLE
minimega: aggressive locking breaks the web interface

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#358]
https://github.com/sandia-minimega/minimega/commit/c506e0bdaa3ce0e8eaeb49d315d2e22d6ad7cc83

has the side effect that when you do something like `read foo`, and `foo` is a long script (taking minutes to complete, which isn't uncommon), the web interface is effectively frozen. 

The web interface backend commands need to safely ignore the lock.

@jcrussell

**Comment by jcrussell** [comment]
Ew. I don't like the idea of ignoring the lock because we don't know what commands the web interface may issue. We could introduce the the notion of read-only commands that don't require the lock but that might complicate things. What if we `fix` the read command -- it runs asynchronously in the background, acquiring the lock before and after each command. Something like:

```
read
read <file,> <file>
read <out,> <id>
clear read [id]
```

Then web/cli/meshage can interleave commands as needed. Calling `read` with no args displays the files that are currently being read, the number of commands executed so far, and whether an error has been encountered. `read <out,> <id,>` would retrieve the output from the executed commands.

There could be some weirdness if you try to `read` two files that launch VMs with the shared `vm config` state.

Thoughts?

**Comment by djfritz** [comment]
Can we do part of this and just have the read command grab the lock between
commands and still block as per the current api?
