### ISSUE TITLE
minimega: extend VNC API

### ISSUE THREAD

**Issue by floren** [sandia-minimega/minimega#426]
The VNC API could use an overhaul. Here's Fritz's suggestion:

```
vnc fb record <host> <vm> <filename>
vnc kb record <host> <vm> <filename>
vnc fb stop <host> <vm>
vnc kb stop <host> <vm>

# show current recordings/playbacks. More info is needed at least on playbacks (time remaining?, % complete...) as well as recordings (time recorded...)
vnc     

# start a playback or restart from the beginning of an existing playback
vnc play <host> <vm> <filename>

# stop playback, but keep the current position in the playback file
vnc stop <host> <vm>

# continue a stopped playback
vnc continue <host> <vm>

# if started, skip the current delay and advance immediately to the next event (@floren's need)
# if stopped, simply play the next event and stop again
vnc step <host> <vm>
```

**Comment by floren** [comment]
@cdshann you want this?

**Comment by djfritz** [comment]
While we're at it, let's add inject capability.

    vnc inject <host> <vm> <kb,mouse> ...

**Comment by cdshann** [comment]
@floren If this can wait until the middle of next week for me to start (need to finish nuke fixes and wrap up qos) then yeah I will take it. Thanks

**Comment by mkunz7** [comment]
Instead of "stop" can we use the word "pause". I think stop implies it resets to the start. 

Floren's need was actually by my request. Sorry to create so much work.

To get a clearer understanding of my need. In some of the complex scripts I write I press next to start an installer then wait for an hour for the installer to finish.

100000000:KeyEvent,true,Alt_L
100000000:KeyEvent,true,n
100000000:KeyEvent,false,n
100000000:KeyEvent,false,Alt_L
3600000000000:PointerEvent,0,0,0
100000000:KeyEvent,true,Alt_L
100000000:KeyEvent,true,f
100000000:KeyEvent,false,f
100000000:KeyEvent,false,Alt_L

When writing these scripts I've been padding them so if the installer takes 20min I give it an hour. This is so we when move between hardware it has a greater chance of working. When debugging I have to sit and wait that extra 40min and with Floren's new skip or step command whatever you want to call it I can tell it to stop waiting.

I can see the value add with single stepping where if I had a better way to determine what is on the screen things can be live.

Additional request with step. Make it so a VNC doesn't have to be running and I can issue a step.
vnc step <host> <vm> 100000000:PointerEvent:0,0,0
vnc step <host> <vm> 100000000:PointerEvent:1,0,0
vnc step <host> <vm> 100000000:PointerEvent:0,0,0
vnc step <host> <vm> 100000000:KeyEvent,true:a
vnc step <host> <vm> 100000000:KeyEvent,false:a

or ideally to make my life easy with a default wait time
vnc step <host> <vm> mousemove <x,y>
vnc step <host> <vm> mouseclick <x,y>
vnc step <host> <vm> mouserightclick <x,y>
vnc step <host> <vm> keydown Shift_L
vnc step <host> <vm> keypress a
vnc step <host> <vm> keyup Shift_L

Most special character key presses require a shift ie question mark
So if I issue:
vnc step <host> <vm> keypress ? 
it would need to do
100000000:KeyEvent,true,Shift_L
100000000:KeyEvent,true,question
100000000:KeyEvent,false,question
100000000:KeyEvent,false,Shift_L

100000000:KeyEvent,true,A
Does not require a shift depending on the OS. In windows it assumes you hit caps lock with the keyevent and types a capital A then undoes capslock.

Similar issue with mouse clicks you have to move there first click then unclick. I would want
vnc step <host> <vm> mouseclick 0,0
to do
100000000:PointerEvent:0,0,0
100000000:PointerEvent:1,0,0
100000000:PointerEvent:0,0,0

Jon's right we'll need to handle that case of not doing anything if it is finished.

I like the inject idea.
vnc inject <host> <vm> <kb,mouse> ...

Just to be clear it would be
vnc inject <host> <vm> file run.vnc

I would want this command to inject and run it and not just inject the file to the host.

Currently I scp the file then issue the command to run it. I usually use the same file name so I have to delete it first as well.

**Comment by mkunz7** [comment]
Another great feature would be to print the comments in VNC files as they are ran.

```
# Alt N
100000000:KeyEvent,true,Alt_L
100000000:KeyEvent,true,n
100000000:KeyEvent,false,n
100000000:KeyEvent,false,Alt_L
# Wait 1 hour 
3600000000000:PointerEvent,0,0,0
# Alt F
100000000:KeyEvent,true,Alt_L
100000000:KeyEvent,true,f
100000000:KeyEvent,false,f
100000000:KeyEvent,false,Alt_L
```

To print a hashtag you do

```
100000000:KeyEvent,true,#
100000000:KeyEvent,false,#
```

Which may cause some issues

**Comment by mkunz7** [comment]
If we can figure out how sikuli https://github.com/sikuli/sikuli vncrobot does .find("a.png") and get it to accurately work that would be a good enhancement as well.

**Comment by jcrussell** [comment]
Closing this based on merging #513 and #676.
