### ISSUE TITLE
minimega: `-recover`

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#496]
It would be interesting to see how much state we could recover from `/tmp/minimega` to continue using an experiment after a crash. Obviously, if the experiment can be restarted, that is the best thing to do. However, if `-recover` can provide enough state that some bits of the experiment can be salvaged, that would be a decent win -- especially experiments with long setup times.

Thinking about this, we probably need to push more state to the `tmp` directory -- perhaps in JSON format so that we can ingest it easily.

**Comment by djfritz** [comment]
This has come up before - we investigated it and it's a lot harder than it
seems at first. Reattaching to orphaned processes is one thing for qemu,
but containers will have a harder time. The networking stack is messy too.
What about vnc playback/recording state? Capture state? Upstream 3rd party
programs?

There are myriad corner cases too, we have to figure out bridges we created
so we can clean them up after reattaching, deal with half-launched vms that
caused us to crash (containers will kill us here), ...

As for json storage of state in the base directory - it rubs against human
readable config/state as per the UNIX philosophy (even though it is
plaintext), and there's no reason we couldn't write a parser for a human
readable / pipelinable file format.

At the end of the day, I think the effort involved would be better spent on
eliminating bugs that cause panics in the first place.

It would be interesting to see how much state we could recover from
/tmp/minimega to continue using an experiment after a crash. Obviously, if
the experiment can be restarted, that is the best thing to do. However, if
-recover can provide enough state that some bits of the experiment can be
salvaged, that would be a decent win -- especially experiments with long
setup times.

Thinking about this, we probably need to push more state to the tmp
directory -- perhaps in JSON format so that we can ingest it easily.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/sandia-minimega/minimega/issues/496>

**Comment by mkunz7** [comment]
Constraining it down is probably a good idea. If we could recreate web and allow vnc record,playback,screenshot I think that would be a good win.

**Comment by mkunz7** [comment]
Minimega crashed on me today after running something for two weeks. I made a limited web interface using python. https://github.com/sandia-minimega/minimega/pull/535/commits/fbf9958a8d10b09613170daf26b7192793006307

**Comment by djfritz** [comment]
This is just too big a lift with the way we store state, maybe someday...
