### ISSUE TITLE
minimega: `vm info` columns

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#510]
`vm info` is getting unruly -- thankfully, we have `.filter` and `.columns`. Some useful fields are missing (e.g. `filesystem` and `hostname` for containers) and some fields can be huge (e.g. `tags`). We certainly need to add the container-specific columns but we already have 24 columns -- when should we stop?

Thoughts?

@djfritz @floren

**Comment by floren** [comment]
Here's my suggestions:

- Pick a smaller subset of fields to display by default. At a first pass, I'd say we should eliminate "bandwidth", "migrate", possibly "bridge", "vcpus", maybe "append", probably "UUID". I'm not sure "bandwidth" even works, I'm highly skeptical of all the bandwidth measurement/reporting in minimega. As for the others, they're probably not super important in general use--I'm usually looking for name, id, how much memory it's got, what networks it's on, and its IPv4 address.

- Add "vm info <kvm,>" and "vm info <container,>" so we can display only a specific type of VM. I understand this is already possible with .filter, but those seem like two use cases where a simpler option would be useful. We could also set up specific sets of fields to display for kvm vs. container, which would compact things a bit.

- Give the capability to define your own default columns *once* rather than at each invocation, so your setup script could say "vm info set-columns id,name,ip,disk" and forever after "vm info" will show the equivalent of running ".columns id,name,ip,disk vm info"

**Comment by djfritz** [comment]
The original idea with `vm info` was to make it pipelinable, which assumed we dumped /everything/ by default. I think that API gets used in this way more than by human inspection, though I may be wrong. 

Setting other defaults in certain ways can be problematic for things like minicli when it tries to merge responses from multiple hosts.

We had a VM-type specific vm info before, but it made things difficult to parse and made the web interface more wonky than it is now. 

I like the idea of a default set of columns to produce, and the ability to change that set. This could be accomplished by the .columns API (API specific persistent column sets...) or as @floren specified. This is a special case, so @floren's solution is probably best. If we do that, there should be a shorthand way to do a one-time "give me all columns" call for ease of parsing, etc. `vm info all` or something.

@jcrussell @floren

**Comment by jcrussell** [comment]
We decided to leave `vm info` as is and add a new API, `vm summary`, that provides a few fields from `vm info`.
