### ISSUE TITLE
More refined scheduling using namespaces

### ISSUE THREAD

**Issue by derhart** [sandia-minimega/minimega#536]
Where on your roadmap is the improvements to scheduling in namespace-enabled minimega? Round-robin is working for us at the moment, but I can foresee us needing a more intelligent approach soon. We can implement a new approach, but I don't want to duplicate effort.

**Comment by jcrussell** [comment]
I don't plan to touch the scheduler for a while -- I'd like to work the bugs out of master and (probably) cut a 2.3 release towards the end of summer. The main lift for 2.4 could be an improved scheduler with a shorter lead time.

What issues are you having with the round-robin scheduler? Perhaps we can make it marginally smarter to suit your needs.

**Comment by djfritz** [comment]
Just echoing @jcrussell - we intentionally decoupled the scheduler from the namespace functionality, and left round-robin as a placeholder. This has come up a few times and we have a good approach for the solution when we eventually get to it. The earliest I can see this happening is August.

**Comment by derhart** [comment]
I'm not sure it's a pressing issue. If you weren't going to look at it until CY17, I might be worried. Can you give me a clue of what your approach will be? Personally I'd like something that accounts for host "load" (however that's calculated) to determine the number of VM instances that can run on the host. That's about as advanced as I'd like. That way if someone short-circuits the typical namespace/meshage deploy strategy and deploys 90 VMs to a single host, any subsequent deployments will most likely ignore the overloaded host.

**Comment by jcrussell** [comment]
Yes, we will try to schedule VMs according to the host "load". However, determining "load" is challenging -- VMs are started in a paused state so we can't know how much memory/CPU they will use when they actually start and the experiment begins (and how things like Kernel Samepage Merging will behave).

**Comment by djfritz** [comment]
There's lot of research on VM placement and non-runtime scheduling (I'm opposed to the mess involved in runtime rescheduling). You can get very good solutions with a multi-level queue scheduler with each level scheduling on one constraint (memory, cpu load, similar vm type, similar network type). It's easy to tune as well to get most any type of schedule you want. 

I assume we'll have a schedule api somewhere to tune that or override with static scheduling (need vm x on node y).

**Comment by djfritz** [comment]
@jcrussell 

A proposed scheduler:

Assumptions:

* there are N physical nodes
* there are X vms to schedule
  * a vm has one or more vlans
  * a vm has a disk or filesystem associated with it
  * a vm has other things, but they generally don't matter
* we don't need to use all physical hosts in a schedule, even if X > N, however:
* we will prefer fanout instead of crazy density. We do this because we generally have performant networks and oversubscribing nodes always comes at a cost. Besides, to enforce greater density, the operator can just provide fewer nodes in the namespace.
* the only tunables should be
  * prefer network locality or vm locality (based on disk image)
  * possibly add a node cooldown tunable as a time.Duration
  * just do round robin
  * maximum vms/node (throw an error if X/max > N)

Approach:

* group VMs by the tunable parameter (vlan, disk/filesystem)
* for V vlan groups (or disk/filesystem groups), modulo across available nodes N. This creates a (hopeful) map of vlan/disk groups to node. If resources fill up, we'll spill over into other nodes as described below.
  * there's an opportunity here to do a tiling solution to match/balance large and small groups to get an optimum placement balance while still prefering the group priority.
* start a dispatcher for each physical node that has VMs assigned to it
  * this doesn't have to be parallel but probably will be because @jcrussell is nuts
* for each dispatcher
  * starting with the largest group assigned to it, begin launching VMs
  * there may a cooldown for this node, in which case we sleep
  * check limits (maximum vms/node, free memory, ...)
    * if we're within limits, launch another vm
    * if we're not within limits, possibly wait longer (# of retries * cooldown?)
    * if we're convinced the node is full, redistribute the remaining vms as new groups to other dispatchers (either re-tile magic or just redistribute to the least taxed nodes). Other dispatchers will have to re-sort and possibly start launching those vms if the groups are larger than those already belonging to the node.
      * if the node has hit it's max vms/node limit already, remove the dispatcher from the table of dispatchers that can have more vms scheduled to it
      * otherwise keep the dispatcher alive until the schedule is done, as VMs may be sent to this dispatcher much later if this is a very "full" schedule.
      * if a dispatcher has to redistribute Y times *without making progress*, remove the dispatcher from the table of dispatchers that can have groups redistributed to it. This is an indicator that the node is actually full.
* if all of the dispatchers are full and there are still VMs to schedule, pause the scheduler, return an error, and give the operator the CLI back. The operator can then add more physical nodes (if available) or wait for KSM, do other magic, or increase the max vms/nodes and ask the scheduler to pick up where it left off (with any dispatchers that haven't already his max vms/node limits back in the queue).                        
  * optionally the operator can cancel the schedule.
  * if cancelled, the operator is responsible for cleaning up (kill, flush, etc.)

**Comment by djfritz** [comment]
Virtually all of the current literature on VM placement asserts that the myriad algorithms give the end user little benefit except in the case where you have SLAs that have to be met. In our case, an SLA would be equivalent to something like "I need vm X to be on a node all by itself because I'm doing some network measurement on the physical interface for it". In that case, we'd want the scheduler to NOT coschedule the vm, and perhaps force the VM to a particular host. That's something the scheduler will always have to be told.

**Comment by djfritz** [comment]
So instead of the last proposal, I think we can simplify this:

* add user tunables
  * "max vms/node" flag (`nsmod ?`, maybe add a schedule sub-api with this one thing in it for later things)
  * force schedule (`vm config schedule <host>`)
  * max coscheduled (`vm config coschedule <max peers>`)
* replace round robin with LLF (least loaded first)
  * for each vm, pick a/the node with the least load (GLOBAL, not namespace specific)
    * (total memory - total commit (memory conf for each vm)) (can be negative)
    * this can be weighted if we can find a good scaling factor, but I think the above is sane for now (consider use cases - we don't tend to launch experiments with WILDLY different memory commits)
      * (total memory - total commit) / ( C * num vms on the host)

That's it - no need for max vms/node or other madness. We could also impose launch limits - don't schedule on a node if the /actual/ free memory is under a certain limit.

**Comment by djfritz** [comment]
Some more context - Most experiments don't have large variations of memory commits for individual VMs, so the above will naturally balance the VM count on physical nodes. It's difficult for a scheduler to infer how VMs might get used. So for example, if you want to favor grouping by network (vlan), that may not be terribly useful if your workload doesn't have any VMs on the same network talking to each other. There is a benefit in having the router on the same node as the vms it serves, and we could add something like that later, but again, that router is going to have to talk to someone else, and so you a lot of that benefit can be eaten away pretty quickly. It's all about how the VMs get used...

There is a clear advantage to having VMs with similar disk images coschedule, but that only plays a factor with you have an experiment that requires significant density. Those experiments are fairly rare, and considering use cases again - when we have very high density experiments we tend to already have very homogeneous disk images and the placement will happen naturally.

I think the new `vm config` parameters give the user enough control in placement when it's necessary or when the known workload for a given VM is known.

**Comment by djfritz** [comment]
This is also simple enough that the load calculation can be swapped out for more complex scenarios as we encounter them.

**Comment by djfritz** [comment]
This also doesn't require constant polling on the node - at most once (to figure out total memory)

**Comment by jcrussell** [comment]
I'm think about changing it from "total memory - memory commit" to "memory commit/total memory". It seems to make more sense to talk about load in terms of a ratio. Similarly, we can compute "cpu commit/number cpus" for cpu load (we currently just sort by cpu commit).

**Comment by djfritz** [comment]
I think the original reason we used the difference instead of the ratio is so that we could apply limits such as 'don't launch vms on hosts with too little free memory'. There is, of course, no reason we can't still do that if we compute on the ratio...

**Comment by djfritz** [comment]
Yep
