### ISSUE TITLE
minimega: hanging namespaces

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#624]
It's possible to hang minimega over meshage with namespaces:

node1: enter a namespace
node2: mesh send all something like vm info

node1, depending on the command, may in turn attempt to mesh send commands, causing a deadlock.

This doesn't need a fix right now, but we should get to it eventually.

@jcrussell

**Comment by jcrussell** [comment]
I thought we decided two head nodes was bad.

We could fix this by making it so that we only ever invoke the local behavior when we receive a command via meshage.

**Comment by jcrussell** [comment]
Whoops...

**Comment by jcrussell** [comment]
We can probably solve this with the `minicli.Command.Source` field. We already use this field to determine whether to do the "fan out" or "local" behavior in `wrapBroadcastCLI` and `wrapVMTargetCLI`. We would need to change these so that they perform the local behavior whenever the Source is a non-zero string. We would also need to change `mesh send` to set the source of the subcommand to a non-zero string.
