### ISSUE TITLE
article: using docker-machine with minimega

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#647]
I wanted to present an alternate approach to containers and see if you guys have any feedback on it. 

https://docs.docker.com/machine/get-started/
Use minimega to spawn up a pool of docker servers.
Use docker-machine to manage the containers on them.
The mini cli could run docker-machine commands to run containers however needed.

Digital ocean wrote a custom driver that interfaces with their cloud. Perhaps we could do the same with mini.
https://www.digitalocean.com/community/tutorials/how-to-provision-and-manage-remote-docker-hosts-with-docker-machine-on-ubuntu-16-04

Discuss.
@floren @djfritz @jcrussell @cdshann @x64x6a

**Comment by djfritz** [comment]
This very explicitly breaks the orchestration and scheduling goals of
minimega - offloading to some other head node, letting other tools schedule
services, and having to hack docker to get it to play with our openvswitch
implementation (or migrate our kvm setup to docker's?)

There's a lot more here than just launching containers, which is the
trivial part of what docker does - so much so that libcontainer isn't even
part of docker anymore (thanks systemd you monster). We either don't need,
don't want, or cannot work with the rest of the docker ecosystem - so why
bother in the first place?

A better proposition may be to ditch our container implementation for
libcontainer (runc, or whatever hipsters call it these days)
https://github.com/opencontainers/runc

We tried this before writing our own, along with lxc and google's lmctfy.
None of these implementations offered a quickly scalable (launch 10k of
these thanks), full-system container implementation that had a networking
stack that we could control. We spent an entire summer with interns
attempting to gut the networking stack in libcontainer for our own with no
meaningful success.

Finally, I just looked at what was involved in actually launching a
container - hardly anything - so I wrote the implementation we have now.
The ONLY hangup we're having now is systemd marshalling access to cgroupfs,
which actually may just be an artifact of our trying to mount our own
cgroup. In fact, this may not even be a systemd issue, as the cgroup mount
logic has changed:

https://www.kernel.org/doc/Documentation/cgroup-v1/cgroups.txt - allows
multiple cgroup hierarchies (which minimega uses)
https://www.kernel.org/doc/Documentation/cgroup-v2.txt - does not allow
multiple cgroup hierarchies

We just haven't looked into it.

A lot of time has been spent stabilizing the container implementation, so
much so that we consider it first class and depend on it for things like
minirouter. On non-systemd debian and ubuntu systems we've had no issues
for several months now, and conservatively we've booted >2 million
containers with minimega in the last 2 months within our own experiments
alone. I'd prefer to investigate the mountpoint issue before looking at
other alternatives.

@floren @jcrussell @cdshann

**Comment by mkunz7** [comment]
I'm not trying to start a war on containers. From my perspective I'm looking at what the community is doing. Openstack has a nova plugin. https://github.com/openstack/nova-docker Digitalocean has a driver. 

Imo I think isolating the dependencies to the user is fine. The way I see it is if I wanted to support containers in my experiment today, I could do so using docker vms with no code change to minimega.  You launch a vm that has all the weird setup requirements of docker. Setup a tap and use docker-machine to connect. Nothing special needed on the host. Yes there is a performance impact running containers virtually instead of natively, but I see the trade off being compatibility with the ever changing community and offloading complexity.

You do lose control of the network stack as well. No doubt, another consequence to this approach. But, you don't lose full control, it is just transferred to the VMs. You could just build experiments with container clouds. Not everyone will be able to live with this restraint, but I think some would.

You could utilize dockers library of prebuilt containers this way.

If we can make current containers work with systemd and iron out the other issues, they could both complement each other extremely well. Docker is exceedingly pervasive, we can't fight it forever.

**Comment by jcrussell** [comment]
One reason that we might want to have docker in our experiments is to support building containers using dockerfiles. This could be a simple way to add a lot of fidelity to our models. Dockerfiles are pretty simple though and we could probably translate them to minimega commands without too much difficulty.

Other than that, I'm not sure why being compatible with the community should be our goal. We should definitely resolve the cgroup mount issues but that seems doable, even on a systemd box. What does being able to launch docker containers vs our containers buy us? We've already identified that there are a lot of costs.

**Comment by mkunz7** [comment]
Container isolation - Support for multiple containers that require modifications to the kernel. (Anything that uses redis)

**Comment by mkunz7** [comment]
Do you really want to spend the man power converting containers? 
it makes it hard to evaluate a vendors product, if we are given a docker container and we modify it to boot with mini containers.

**Comment by jcrussell** [comment]
Are you referring to docker's privileged containers? They remove isolation and allow the container to change properties of the host OS.

When the alternative would be trying to stay in sync with docker internals, probably. There's a lot of man power required to switch to docker containers and work out all the bugs -- at least a few months. The dockerfile API isn't going to change very much and writing the tool would take a few days.

**Comment by mkunz7** [comment]
Because the container is in a VM we can modify the kernel on the VM without touching the base OS's kernel. Which adds isolation in and of itself which is a good thing in this case.

**Comment by jcrussell** [comment]
Wait, if you just want to launch a VM that creates docker containers, why can't you do that with existing minimega? If the VM has `miniccc` installed, you can push/pull dockerfiles and launch containers using `cc` commands.

Do you want the containers to show up in the list of VMs? That seems like a big lift for a niche use case. You could dump a bunch of info into the VM's tags about the running containers and build something on top of minimega to display that info.

Am I missing something?

**Comment by mkunz7** [comment]
You can. Doesn't seem you are missing anything, I just think we should make a article on using docker inside VMs. That way if someone asks how does mini support containers you can point them at both methods. 

I see the value of integration with the cli, but its not needed.

**Comment by jcrussell** [comment]
That makes sense. I, and I think Fritz, interpreted this issue as wanting to replace minimega's containers with some minimega/docker hybrid. If you want to write an article describing how to deploy docker containers inside VMs orchestrated by minimega, please go ahead.

**Comment by jcrussell** [comment]
If you want to figure this out, feel free. We're not going to track it though.
