### ISSUE TITLE
minimega: qos rate limiting is making interfaces unavailable

### ISSUE THREAD

**Issue by cdshann** [sandia-minimega/minimega#752]
The current rate limiting implementation (using the token bucket filter queue discipline) will eventually make an interface unusable. I believe this is because of the latency parameter which is dropping packets prematurely.

We should also remove the burst parameter to enforce a hard rate limit.

minimega is currently using the following traffic control command to implement rate limiting
`tc qdisc add dev <interface> root tbf rate <rate> burst 2048 latency 100ms`

**Comment by jasoncontrib** [comment]
I ran a large (~3000 node) test and the loss and delay QoS constraints seem to work fine.

After adding a rate constraint with `qos add all 0 rate 1 mbit`, however, caused pings to shoot up to 10-20 seconds between endpoints, even though `tc -s qdisc ls dev mega_tap2` on the physical host for one of the endpoints is not showing that packets are being `dropped` or `overlimits`. On a subsequent run, I couldn't reproduce this behavior.

**Comment by jasoncontrib** [comment]
It seems that a large backlog is building up, and more critically, not being drained, even after ceasing traffic-generating activity on the endpoints:

```
qdisc netem 1: root refcnt 2 limit 1000 loss 0.25%
 Sent 918177 bytes 12308 pkt (dropped 26, overlimits 0 requeues 0)
 backlog 0b 0p requeues 0
qdisc tbf 2: parent 1: rate 100Mbit burst 52425b lat 100.0ms
 Sent 151393 bytes 1881 pkt (dropped 0, overlimits 220 requeues 0)
 backlog 34212b 177p requeues 0
```

**Comment by jasoncontrib** [comment]
Increasing `DEFAULT_LATENCY` to 1000ms eliminated the backlog, but the issue remains (interface eventually becomes unusable).

Here's how I reproduce the issue:

1. Launch minimega
2. Create a small test network and apply QoS:
```
namespace qostestA
web 9001
# some endpoints
vm config filesystem /data/minimega/images/containerfs
vm config net netA,00:11:22:33:44:55
vm launch container host1
vm config net netA,AA:BB:CC:DD:EE:FF
vm launch container host2
# and a router
vm config preinit /data/minimega/images/minirouterfs/preinit
vm config filesystem /data/minimega/images/minirouterfs
vm config net netA core
vm launch container routerA
# routerA
router routerA interface 0 10.0.0.1/24
#router routerA interface 1 20.0.0.1/24
router routerA dhcp 10.0.0.1 range 10.0.0.2 10.0.0.10
# do static dhcp for known mac addresses
router routerA dhcp 10.0.0.1 static 00:11:22:33:44:55 10.0.0.100
router routerA dhcp 10.0.0.1 static AA:BB:CC:DD:EE:FF 10.0.0.101
# can also do things like dhcp router, dhcp dns
#router routerA route ospf 0 0
#router routerA route ospf 0 1
router routerA commit

vm start all
qos add all 0 rate 1 mbit
```
4. `/iperf -s -i 1` on `host2`
5. `/iperf -c host2 -i 1 -t 3600` on `host1`
6. Watch as traffic grinds to a halt after ~30 seconds.

**Comment by jasoncontrib** [comment]
The root cause seems to be a backlog of packets building up in the packet queue, leading to severely delayed (10-20s) packets. Not sure why this is happening, since the `latency` parameter of `tbf` is supposed to prevent exactly this...

Using `tcpdump`, I can see the delayed ARP responses being sent back much later, and iperf shows packets continuing to be sent to the server for 10-20s even after the client is killed.

This could explain a lot:
"The NetEm qdisc does not work in conjunction with other qdiscs."
https://www.bufferbloat.net/projects/codel/wiki/Best_practices_for_benchmarking_Codel_and_FQ_Codel/#the-netem-qdisc-does-not-work-in-conjunction-with-other-qdiscs


Things I tried:

1. switching queuing disciplines from `tbf` to `htb`
result: no improvement, still grinds to a halt with rate limiting applied


2. turning off tcp offload with ethtool on the CCC physical hosts (tso, gso, rso, rx checksumming, tx checksumming offloads)
result: no improvement, still grinds to a halt with rate limiting applied


3. using `netem`'s `rate` option and getting rid of `tbf`
result: backlog still accumulates with default `limit` of `1000`, but reducing `limit` to `10` packets significantly helps


4. increasing the `DEFAULT_LATENCY` value from `100ms` to `1000ms` in QoS.go
result: no improvement; although backlog no longer builds up in tc qdisc stats, it still results in the same problematic behavior


5. switching from `DEFAULT_LATENCY` value to a `DEFAULT_LIMIT` value of `10000b`
result: no improvement


6. swapping order of chain so that netem is a leaf node of the tc chain, instead of the root.
(see first few comments in this script, which say that tbf / htb must come BEFORE netem in the chain: https://github.com/dmitrymurashenkov/lossy/blob/master/lossy)
(http://superuser.com/a/147434)
(this script, too: https://gist.githubusercontent.com/denilsonsa/5176e1c9b6a119594ce0/raw/6168c853ca875516025d291b2ff25105891f44aa/slow)
result: no improvement; still the same problematic behavior.


7. reducing the `mega_tapXX` interfaces' `txqueuelen` on the CCC physical hosts from the default of `1000` to `20`: http://serverfault.com/q/629838
`ifconfig mega_tap0 txqueuelen 20`
result: no improvement, same behavior as before


8. eliminate `netem` and use `htb` only
`tc qdisc add dev mega_tap0 root handle 0: htb default 12`
`tc class add dev mega_tap0 parent 0: classid 0:12 htb rate 1Mbit ceil 1Mbit`
result: works great at rate limiting traffic, but without `netem`, we can't emulate delay and packet loss


9. using open vswitch's QoS options via ovs-vsctl
`ovs-vsctl -- set Port vnet2 qos=@newqos -- --id=@newqos create QoS type=linux-htb other-config:max-rate=1000000 queues=0=@q0 -- --id=@q0   create   Queue   other-config:min-rate=1000000 other-config:max-rate=1000000`
result: ovs-vsctl seems to use `tc` and `htb` to create its QoS queues, so it effectively does the same thing as above. works great, but can't emulate delay and packet loss


10. using open vswitch's ingress policing
`ovs-vsctl set interface mega_tap0 ingress_policing_rate=1000000`
result: works great at rate limiting traffic again, but same caveats as above: no packet loss and delay emulation. also, this is ingress policing, not egress rate-limting / queueing as in the other approaches. furthermore, the actual rate limit achieved is close but not quite the desired rate (e.g. `ingress_policing_rate=1000000` on both endpoints results in `iperf` showing ~130 megabit/s)



I have a few test branches in my fork for swapping htb, tbf, and netem around, if anyone wants to take a look.

For now, we could do the following:

1. using only `netem`, because: 1) it does include a rate parameter that supposedly replaces TBF, simplifying the code in `qos.go`, and 2) because it seems to have adverse interactions with other qdiscs like `htb` and `tbf`

2. setting `netem limit` to something low (e.g. 1 packet, 10 packets, OR possibly auto-calculated?), to prevent a backlog from accumulating. Rationale for setting limit to 1 packet: at low rates (e.g. 100 kbit), the 10 packet limit still results in long latencies if the backlog fills up to 10 packets. Also, a 1 packet queue length seems to applicable when using `htb` too, via `ovs-vsctl` or `tc`: `direct_qlen` is 1, and the backlog never grows beyond 1 packet.
