### ISSUE TITLE
minimega/miniccc: possible race

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#775]
Seeing occasional problems sending a file and then trying to exec it. Seems like miniccc isn't waiting until the file is written before trying to exec it but need to triage.

**Comment by djfritz** [comment]
Working on this today.

**Comment by csymonds** [comment]
I turned on debugging in miniccc and ran a few tests (and added a few extra debug lines). Mux is definitely attempting to process the exec command before the file command is completed:

2016/11/29 23:46:33 DEBUG heartbeat.go:39: sending heartbeat
2016/11/29 23:46:34 DEBUG mux.go:47: new message: COMMAND
2016/11/29 23:46:34 DEBUG commands.go:16: processCommand &{13 false [] [protonuke] [] 0  ip=30.0.0.2 []}
2016/11/29 23:46:34 INFO files.go:64: requesting file protonuke
2016/11/29 23:46:34 DEBUG mux.go:47: new message: COMMAND
2016/11/29 23:46:34 DEBUG files.go:84: recvFiles: message sent _(I added this one)
(I also added in a debug line in files.go when a response is received, but we never get there)_
2016/11/29 23:46:38 DEBUG heartbeat.go:19: periodic

**Comment by djfritz** [comment]
The mux used to use buffered channels to work around this:

https://github.com/sandia-minimega/minimega/blob/93cd5954e895965b804ab9cfb592fd3335d58e51/src/ron/ron.go#L134

In the old version of the code, as long as the command asking to grab a file doesn't get more than 1024 commands down the queue, the file receive operation will be fine. 

This has been broken since October 19 with https://github.com/sandia-minimega/minimega/commit/6f4b2101a088d1693c3dd5ae2c2d22c91be3786a

The buffered channel is itself a bandaid. I'll work up a better solution today.

**Comment by djfritz** [comment]
@jcrussell

**Comment by djfritz** [comment]
So the buffered channel solution actually will work here. The commandChan is a map of commands (all the new commands for the client), so the mux loop will only push on commandChan once per heartbeat. In a given batch of commands, a command that does a file receive operation will get queued along with any other messages in c.in. What this means is that the file receive operation only has to complete in TIMEOUT * buffer depth time. There's an exception with tunnel traffic, but that doesn't create a deadlock since it's in a different code path. 

There's no way to hit a full channel here because the client would have long timed out and disconnected before allowing 1K command updates to get queued.
