### ISSUE TITLE
miniweb: ganglia-like view for host and VM stats

### ISSUE THREAD

**Issue by bjwrigh** [sandia-minimega/minimega#857]
Let's do something like this: 

https://en.wikipedia.org/wiki/Ganglia_(software)#/media/File:ScalableGridEngineGanglia2.png

for the host page on miniweb

**Comment by djfritz** [comment]
Heck yea. I've wanted ganglia style plots since the first version of the
web interface.

On Feb 7, 2017 11:44 AM, "Brian W" <notifications@github.com> wrote:

Let's do something like this:

https://en.wikipedia.org/wiki/Ganglia_(software)#/media/File:
ScalableGridEngineGanglia2.png

for the host page on miniweb

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sandia-minimega/minimega/issues/857>, or mute the thread

**Comment by jcrussell** [comment]
Is it fine if you only have history for how long the page has been open? Don't really want to store this in minimega. I guess it could be stored in miniweb.

**Comment by mkunz7** [comment]
before rewriting the wheel, have we looked at munin?

http://demo.munin-monitoring.org/

**Comment by csymonds** [comment]
This has been folded into #1048 for the new miniweb work
