### ISSUE TITLE
igor: batch processing

### ISSUE THREAD

**Issue by floren** [sandia-minimega/minimega#883]
We should accept some form of scripting so a user can specify "When 100 nodes become available, reserve them and run the following script. When the script exits, the reservation can be freed".

**Comment by floren** [comment]
See #884

**Comment by afbagwell** [comment]
Igor 2.x will preserve the command line interface which users can interact with on the client side through bash scripting. However due to the new client-server architecture, security posture and REST API design, users will not be allowed to upload scripts to be run on the head cluster node. Also, no further enhancements will be made to Igor 1.x.
