### ISSUE TITLE
disk inject is broken

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#941]
```
disk snapshot /home/ubuntu/tinycore.qcow tinysnap
disk inject tinysnap files /home/ubuntu/a:/a
vm config disk /data/mmfiles/tinysnap
vm launch kvm tiny
vm start tiny
Error (server): cannot fetch backing image from outside files directory: /home/ubuntu/tinycore.qcow
```

Nothing in debug logs

This used to work.

**Comment by jcrussell** [comment]
There's an error:

```
Error (server): cannot fetch backing image from outside files directory: /home/ubuntu/tinycore.qcow
```

We're trying to encourage people to put their images in /tmp/minimega/files so that the same scripts that work on a single machine can move to a whole cluster. One precondition for this is that the files can be accessed by any machine in the cluster (which happens automatically when it is copied into /tmp/minimega/files). If you copy `tinycore.qcow` into the files directory and use `tinysnap` as the disk path, this should work.

**Comment by mkunz7** [comment]
Ok that's just me being dumb late at night. That works, if we are making this change we should put a line at the end of disk API to say:

Disks can only be injected into if they are located in the files directory.

And we should reference the right file instead of just what was received. 

Error (server): Was expecting backing file to be in files directory: /tmp/minimega/files/tinycore.qcow received /home/ubuntu/tinycore.qcow
